#DB 설정
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/bapay_public
#    driver-class-name: org.postgresql.Driver
#   username: bapay_admin
#    password: ljhzz168254
    
#Server Default Port : 6000
server:
  port: 8081